// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateUserStatusProtobuf.proto

package com.wblog.proto;

public final class UpdateUserStatusProto {
  private UpdateUserStatusProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface updateUserStatusReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:updateUserStatusReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nickName = 1;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>string nickName = 1;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>int64 status = 2;</code>
     */
    long getStatus();
  }
  /**
   * Protobuf type {@code updateUserStatusReq}
   */
  public  static final class updateUserStatusReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:updateUserStatusReq)
      updateUserStatusReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use updateUserStatusReq.newBuilder() to construct.
    private updateUserStatusReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private updateUserStatusReq() {
      nickName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new updateUserStatusReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private updateUserStatusReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 16: {

              status_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.class, com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.Builder.class);
    }

    public static final int NICKNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nickName_;
    /**
     * <code>string nickName = 1;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private long status_;
    /**
     * <code>int64 status = 2;</code>
     */
    public long getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nickName_);
      }
      if (status_ != 0L) {
        output.writeInt64(2, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nickName_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq)) {
        return super.equals(obj);
      }
      com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq other = (com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq) obj;

      if (!getNickName()
          .equals(other.getNickName())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code updateUserStatusReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:updateUserStatusReq)
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.class, com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.Builder.class);
      }

      // Construct using com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nickName_ = "";

        status_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusReq_descriptor;
      }

      @java.lang.Override
      public com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq getDefaultInstanceForType() {
        return com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq build() {
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq buildPartial() {
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq result = new com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq(this);
        result.nickName_ = nickName_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq) {
          return mergeFrom((com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq other) {
        if (other == com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq.getDefaultInstance()) return this;
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>string nickName = 1;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 1;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <code>int64 status = 2;</code>
       */
      public long getStatus() {
        return status_;
      }
      /**
       * <code>int64 status = 2;</code>
       */
      public Builder setStatus(long value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:updateUserStatusReq)
    }

    // @@protoc_insertion_point(class_scope:updateUserStatusReq)
    private static final com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq();
    }

    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<updateUserStatusReq>
        PARSER = new com.google.protobuf.AbstractParser<updateUserStatusReq>() {
      @java.lang.Override
      public updateUserStatusReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new updateUserStatusReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<updateUserStatusReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<updateUserStatusReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wblog.proto.UpdateUserStatusProto.updateUserStatusReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface updateUserStatusResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:updateUserStatusRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 code = 1;</code>
     */
    long getCode();

    /**
     * <code>string desc = 2;</code>
     */
    java.lang.String getDesc();
    /**
     * <code>string desc = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescBytes();

    /**
     * <code>bool result = 3;</code>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code updateUserStatusRes}
   */
  public  static final class updateUserStatusRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:updateUserStatusRes)
      updateUserStatusResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use updateUserStatusRes.newBuilder() to construct.
    private updateUserStatusRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private updateUserStatusRes() {
      desc_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new updateUserStatusRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private updateUserStatusRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              desc_ = s;
              break;
            }
            case 24: {

              result_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.class, com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private long code_;
    /**
     * <code>int64 code = 1;</code>
     */
    public long getCode() {
      return code_;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object desc_;
    /**
     * <code>string desc = 2;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      }
    }
    /**
     * <code>string desc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private boolean result_;
    /**
     * <code>bool result = 3;</code>
     */
    public boolean getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0L) {
        output.writeInt64(1, code_);
      }
      if (!getDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
      }
      if (result_ != false) {
        output.writeBool(3, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, code_);
      }
      if (!getDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
      }
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes)) {
        return super.equals(obj);
      }
      com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes other = (com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getDesc()
          .equals(other.getDesc())) return false;
      if (getResult()
          != other.getResult()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCode());
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResult());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code updateUserStatusRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:updateUserStatusRes)
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.class, com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.Builder.class);
      }

      // Construct using com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0L;

        desc_ = "";

        result_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wblog.proto.UpdateUserStatusProto.internal_static_updateUserStatusRes_descriptor;
      }

      @java.lang.Override
      public com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes getDefaultInstanceForType() {
        return com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes build() {
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes buildPartial() {
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes result = new com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes(this);
        result.code_ = code_;
        result.desc_ = desc_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes) {
          return mergeFrom((com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes other) {
        if (other == com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes.getDefaultInstance()) return this;
        if (other.getCode() != 0L) {
          setCode(other.getCode());
        }
        if (!other.getDesc().isEmpty()) {
          desc_ = other.desc_;
          onChanged();
        }
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long code_ ;
      /**
       * <code>int64 code = 1;</code>
       */
      public long getCode() {
        return code_;
      }
      /**
       * <code>int64 code = 1;</code>
       */
      public Builder setCode(long value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object desc_ = "";
      /**
       * <code>string desc = 2;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string desc = 2;</code>
       */
      public Builder setDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        desc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       */
      public Builder clearDesc() {
        
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string desc = 2;</code>
       */
      public Builder setDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        desc_ = value;
        onChanged();
        return this;
      }

      private boolean result_ ;
      /**
       * <code>bool result = 3;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>bool result = 3;</code>
       */
      public Builder setResult(boolean value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool result = 3;</code>
       */
      public Builder clearResult() {
        
        result_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:updateUserStatusRes)
    }

    // @@protoc_insertion_point(class_scope:updateUserStatusRes)
    private static final com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes();
    }

    public static com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<updateUserStatusRes>
        PARSER = new com.google.protobuf.AbstractParser<updateUserStatusRes>() {
      @java.lang.Override
      public updateUserStatusRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new updateUserStatusRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<updateUserStatusRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<updateUserStatusRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wblog.proto.UpdateUserStatusProto.updateUserStatusRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateUserStatusReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateUserStatusReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_updateUserStatusRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_updateUserStatusRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036UpdateUserStatusProtobuf.proto\032\037google" +
      "/protobuf/timestamp.proto\"7\n\023updateUserS" +
      "tatusReq\022\020\n\010nickName\030\001 \001(\t\022\016\n\006status\030\002 \001" +
      "(\003\"A\n\023updateUserStatusRes\022\014\n\004code\030\001 \001(\003\022" +
      "\014\n\004desc\030\002 \001(\t\022\016\n\006result\030\003 \001(\010B(\n\017com.wbl" +
      "og.protoB\025UpdateUserStatusProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_updateUserStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_updateUserStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateUserStatusReq_descriptor,
        new java.lang.String[] { "NickName", "Status", });
    internal_static_updateUserStatusRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_updateUserStatusRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_updateUserStatusRes_descriptor,
        new java.lang.String[] { "Code", "Desc", "Result", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
